// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIOSuZ3I7_EaQ6Vbdh88uHuExFjeOjPQ',
    appId: '1:789071528630:web:d9d2c624a5e10501ac5c17',
    messagingSenderId: '789071528630',
    projectId: 'ez-bank-d74ab',
    authDomain: 'ez-bank-d74ab.firebaseapp.com',
    storageBucket: 'ez-bank-d74ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_-neGt366UIYPqR2AyHBV-QCqMR2OpmI',
    appId: '1:789071528630:android:3c4e05d15ee062a4ac5c17',
    messagingSenderId: '789071528630',
    projectId: 'ez-bank-d74ab',
    storageBucket: 'ez-bank-d74ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4V5q8tEJb-_mwq7Sp_T6i0n790rRSz8',
    appId: '1:789071528630:ios:7a3106c2a9287c7dac5c17',
    messagingSenderId: '789071528630',
    projectId: 'ez-bank-d74ab',
    storageBucket: 'ez-bank-d74ab.appspot.com',
    iosClientId: '789071528630-n9anujnehdvo2mig8jquld7uh43fhi2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa4V5q8tEJb-_mwq7Sp_T6i0n790rRSz8',
    appId: '1:789071528630:ios:7a3106c2a9287c7dac5c17',
    messagingSenderId: '789071528630',
    projectId: 'ez-bank-d74ab',
    storageBucket: 'ez-bank-d74ab.appspot.com',
    iosClientId: '789071528630-n9anujnehdvo2mig8jquld7uh43fhi2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezBank',
  );
}
